yarnPath: .yarn/releases/yarn-3.5.1.cjs
enableScripts: false
packageExtensions:
  posthtml-component@*:
   dependencies:
      posthtml: '*'
  posthtml-expressions@*:
    dependencies:
      posthtml: '*'